### ISSUE TITLE
failed to create dashboard 

### ISSUE THREAD

**Issue by Shawn71** [avinor/terraform-azurerm-dashboard#10]
Hi ,

I just follow you terraform code and try to create dashboard ,but got below error outputs
![image](https://github.com/avinor/terraform-azurerm-dashboard/assets/19188604/32905b82-30a4-4426-a285-bcc88a7fcf0f)

but I am sure that there is no need  to re-authenticate , you can see below:
![image](https://github.com/avinor/terraform-azurerm-dashboard/assets/19188604/47b2b2dc-7fa0-4bae-8461-1e9dba7151d6)

do you have any idea about this ? really thanks

**Comment by yngveh** [comment]
This repo is no longer maintained, closing the issue.
